#
# Authors: Patrizio Bertoni patrizio.bertoni.89@gmail.com
#
# Main AI reference: https://chat.deepseek.com/a/chat/s/209caf2a-1b78-43fa-aa9b-13f6443545d0
#

jekyll:
	docker buildx build -f ./ubuntu.Dockerfile -t pbertoni/jekyll .
